refactor: stop destructuring params as it caused an error when calling remotely
error: The module's source code could not be parsed: Expected ',', got ':' at https://deno-utils.pages.dev/regex-replace.ts:26:30